import Link from "next/link";
import { ArrowRight,ArrowDown,BookOpen,Workflow,Boxes,Coins,Search,Command } from "lucide-react";
import { SectionHead,CTA } from "@/components/Primitives";
import { courseModules,sourceLessonCount } from "@/data/course";
import { roadmap,workflows,tools,useCases,prompts,projects } from "@/data/library";

export default function Home(){return <>
 <section className="hero"><div className="ribbon"/><div className="stat-float glass sf1"><strong>{courseModules.length}</strong><span>modul lengkap</span></div><div className="stat-float glass sf2"><strong>{useCases.length}</strong><span>contoh use case</span></div><div className="stat-float glass sf3"><strong>{prompts.length}</strong><span>prompt siap pakai</span></div><div className="stat-float glass sf4"><strong>{projects.length}</strong><span>ide project</span></div><div className="container hero-content"><span className="eyebrow"><span className="dot"/>Belajar AI · Bahasa Indonesia</span><h1>Belajar AI dari Nol Sampai Bisa Dipakai Buat <span>Kerja, Bisnis, dan Automation.</span></h1><p className="hero-copy">Mulai dari dasar, lanjut ke tools dan workflow, lalu bangun automation, RAG, dan agent. Pelan-pelan, satu project setiap tahap.</p><div className="hero-actions"><Link href="/course" className="btn btn-primary">Mulai Belajar <ArrowRight size={16}/></Link><Link href="/roadmap" className="btn">Lihat Roadmap <ArrowDown size={16}/></Link></div><div className="eyebrow" style={{marginTop:34,textTransform:"none",letterSpacing:0}}>{sourceLessonCount} lesson <ArrowRight size={12}/> Latihan <ArrowRight size={12}/> Project <ArrowRight size={12}/> Portfolio</div></div></section>
 <section className="section section-dark"><div className="container"><SectionHead no="01" title="AI itu lebih dari sekadar tanya-jawab." lead="Kalau dipakai dengan benar, AI bisa membantu riset, menulis, desain, sampai menjalankan workflow. Di sini kamu belajar urutannya, bukan dilempar ke kumpulan istilah."/><div className="grid grid-4">{[["01","Pahami","Kenalan dengan konsepnya pakai contoh sederhana."],["02","Coba","Pakai tool untuk satu pekerjaan nyata."],["03","Rangkai","Gabungkan langkahnya jadi workflow."],["04","Buktikan","Selesaikan project dan simpan hasilnya."]].map(x=><div className="glass card" key={x[0]}><div className="card-top"><span>/{x[0]}</span><span className="dot"/></div><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
 <section className="section"><div className="container"><SectionHead no="02" title="Satu roadmap. Tidak muter-muter." lead="Mulai dari kemampuanmu sekarang. Setiap level punya hasil dan project yang jelas."/><div className="grid grid-3">{roadmap.slice(0,6).map(r=><div className="glass card" key={r.level}><div className="card-top"><span>LEVEL 0{r.level}</span><span>{r.lessons}</span></div><h3>{r.title}</h3><p>{r.learn}</p><ul className="list"><li>{r.output}</li><li>{r.project}</li></ul></div>)}</div><Link href="/roadmap" className="btn" style={{marginTop:24}}>Buka roadmap lengkap <ArrowRight size={15}/></Link></div></section>
 <section className="section section-dark"><div className="container"><SectionHead no="03" title="Empat track, satu operating system." lead="Belajar berdasarkan hasil yang ingin dibangun, bukan mengejar sertifikat tanpa artefak."/><div className="grid grid-4">{[[BookOpen,"AI Operator","Riset, writing, docs, dan kerja harian."],[Workflow,"Workflow Builder","Sistem content, admin, dan business ops."],[Boxes,"Agentic Builder","API, RAG, tool calling, orchestration."],[Coins,"AI Monetizer","Service, product, portfolio, dan delivery."]].map(([Icon,title,copy])=>{const I=Icon as typeof BookOpen;return <div className="glass card" key={String(title)}><I className="blue" size={25}/><h3>{String(title)}</h3><p>{String(copy)}</p></div>})}</div></div></section>
 <section className="section"><div className="container"><SectionHead no="04" title="Belajar satu modul, lalu langsung praktik." lead="Semua lesson diambil dari dokumen materi: ada penjelasan, contoh, latihan, prompt, cek pemahaman, dan tugas kecil."/><div className="grid grid-3">{courseModules.slice(0,6).map(m=><Link className="glass card" href={`/course/${m.slug}`} key={m.slug}><div className="card-top"><span>MODUL {String(m.number).padStart(2,"0")}</span><span className="pill">{m.difficulty}</span></div><h3>{m.title}</h3><p>{m.description}</p><div style={{marginTop:18,fontSize:12,color:"#75aaff"}}>{m.lessons.length} lesson · {m.duration}</div></Link>)}</div></div></section>
 <section className="section section-dark"><div className="container"><SectionHead no="05" title="Resource yang langsung kepakai." lead="Cari tool, salin prompt, ikuti workflow, atau pilih project sesuai level."/><div className="grid grid-3">{[[Search,"Tools Directory",`${tools.length} tools terkurasi`,`/tools`],[Command,"Prompt Library","Template dengan variabel dan cara pakai","/prompts"],[Workflow,"Workflow Recipes",`${workflows.length} sistem step-by-step`,`/workflows`]].map(([Icon,title,copy,href])=>{const I=Icon as typeof Search;return <Link className="glass card" key={String(title)} href={String(href)}><I className="blue"/><h3>{String(title)}</h3><p>{String(copy)}</p><span className="pill">Explore <ArrowRight size={11}/></span></Link>})}</div></div></section>
 <section className="section"><div className="container"><SectionHead no="06" title="Belajar menjual skill tanpa janji berlebihan." lead="Kamu akan belajar memilih masalah, membatasi pekerjaan, membuat hasil yang jelas, dan menunjukkannya lewat case study."/><div className="grid grid-3"><div className="glass card"><div className="metric blue">01</div><h3>Pilih masalah</h3><p>Cari pekerjaan yang lambat, berulang, atau sering bikin error.</p></div><div className="glass card"><div className="metric blue">02</div><h3>Buat paket</h3><p>Jelaskan apa yang kamu kerjakan, hasilnya apa, dan batasnya di mana.</p></div><div className="glass card"><div className="metric blue">03</div><h3>Tunjukkan bukti</h3><p>Buat demo dan case study dari project yang sudah selesai.</p></div></div></div></section><CTA/>
 </>}
